### ISSUE TITLE
Unable to dispatch other actions within apiOk()

### ISSUE THREAD

**Issue by calvinnwq** [FredericHeem/redux-act-async#10]
If I wanted to dispatch other actions together with the "ok" action, I can't do so right now.

I think a way to do it is to allow adding a callback option for each action which when called is passed the dispatch.

PR ~~#9~~ #11

**Comment by FredericHeem** [comment]
Redux middlewares are designed to do so.

**Comment by calvinnwq** [comment]
Updated with a new PR for this. #11

**Comment by calvinnwq** [comment]
Might want to include instructions in the README about specifying options for `payloadReducer`, `metaReducer` and `callback`

**Comment by bradarv90** [comment]
This same issue was attempted to be fixed with PR #6. You can dispatch the next action in the then clause of the promise

**Comment by FredericHeem** [comment]
Can we close this issue now ?
