### ISSUE TITLE
Why doesn't options.rethrow default to true?

### ISSUE THREAD

**Issue by tylercollier** [FredericHeem/redux-act-async#20]
Consider this function in my login component:

```
formSubmit() {
  login({email, password}).then(res => {
    console.log('Login worked')
  }
}
```

With the current code, if the login fails (say with a 401), I'll see the message `Login worked` printed to the console. That's because, by default, redux-act-async doesn't rethrow errors. Why isn't it the default to rethrow errors? Without reading the source code to discover `options.rethrow`, there is no way to catch errors.

The current README is wrong. It says:

> In a nutshell, the following code:...
> is equivalent to:
> ...
> .catch(err => {
>      dispatch(loginError(err))
>      throw err;
>    })

... but it's not equivalent. That `throw` at the end doesn't happen unless I specify `{ rethrow: true }` in the options.

**Comment by FredericHeem** [comment]
Thanks a lot for your feedback, the README has been updated with regards to the `rethrow` option.

**Comment by tylercollier** [comment]
I see you changed to have rethrow as the default in 0.15.0. I think that would be a breaking change right, and a major version release is thus warranted if you're using [semver](http://semver.org/).

**Comment by FredericHeem** [comment]
Since it is still a 0.x lib, any breaking change is permitted. Still, I do apologise for any wasted time for this breaking behaviour.

**Comment by tylercollier** [comment]
Ah, good to know, thanks. Fortunately I happened to catch the version change as I was looking for something else, so no time wasted. Any reason it's in 0.x instead of 1.x?

**Comment by a-sane** [comment]
Hi there,

Maybe you can update Usage section in current README about `noRethrow: true` option, because i had confusing uncaught error while following Usage section example and call async fetch action with server error response - confusing because i'm catched all errors in promise, but still had uncaught error from createActionAsync, so I had to look source code and this issue to find reasons of this behavior.

Thanks!
