### ISSUE TITLE
Version 0.16.0?

### ISSUE THREAD

**Issue by osharper** [FredericHeem/redux-act-async#28]
Just wanted to ask about 0.16.0 version mentioned [here](https://github.com/FredericHeem/redux-act-async/issues/21#issuecomment-251489984). I'm also facing this babel issue but it seems like npm and github know nothing about 0.16

**Comment by FredericHeem** [comment]
Sorry for my mistake, it's 0.15 which has been released.

**Comment by dkfiresky** [comment]
@osharper you can find 0.16.0 [here](https://github.com/FredericHeem/redux-act-async/releases/tag/v0.16.0).

**Comment by osharper** [comment]
Sorry, misread 1.5.0 as 0.15.0 :) thanks for a quick reply and shame on me for a delayed reaction.
