### ISSUE TITLE
Unable to have payloadReducer or metaReducer

### ISSUE THREAD

**Issue by calvinnwq** [FredericHeem/redux-act-async#7]
It seems that you had added a way to pass payloadReducer and metaReducer via options to `createActionAsync`, but currently these don't work. Could probably make it work by finding a way to pass args to the actions.[request, ok, error]. Something like:

`dispatch(actions.request(...args))`

Also, if it did work, is there a way to have different payloadReducer or metaReducer for each action?

**Comment by FredericHeem** [comment]
I'll add a bunch of unit tests to make sure `payloadReducer` and `metaReducer ` can be passed as parameter.

**Comment by FredericHeem** [comment]
Please have a look at the new unit test which passes payloadReducer and metaReducer as parameters: 
https://github.com/FredericHeem/redux-act-async/blob/master/test/createActionAsyncTest.js#L128

**Comment by calvinnwq** [comment]
I think that the point of the payloadReducer/metaReducer from redux-act is to be able to shape the payload from the arguments passed to the action. This is currently what I think is missing.

Here's an example. In many async actions, the parameters for the request and ok/error are different.

e.g.
```
const subredditActions = {
  request: createAction('SUBREDDIT_REQUEST', (subreddit) => ({ subreddit })),
  ok: createAction('SUBREDDIT_OK', (subreddit, response) => ({ subreddit, response })),
  error: createAction('SUBREDDIT_ERROR', (subreddit, response) => ({ subreddit, response })),
};
```

And in the reducers, you might need the argument in the payload (this is what the payloadReducer does). It allows you to take the 'subreddit' parameter and pass it along in the payload Object (similarly for metaReducer).

```
const reducer = createReducer({
  [subredditActions.request]: (state, payload) => {
    return {
      ...state,
      [payload.subreddit]: {
        isLoading: true
      }
    };
  },
  [subredditActions.ok]: (state, payload) => {
    return {
      ...state,
      [payload.subreddit]: {
        isLoading: false,
        response: payload.response
      }
    };
  },
  [subredditActions.error]: (state, payload) => {
    return {
      ...state,
      [payload.subreddit]: {
        isLoading: false,
        response: payload.response,
        error: true
      }
    };
  },
}, {});
```

**Comment by FredericHeem** [comment]
Let's configure a different payloadReducer and metaReducer for `request`, `ok` and `error` actions, it makes senses.

**Comment by FredericHeem** [comment]
Please have a look at the new version 0.6.2.

**Comment by calvinnwq** [comment]
I think you're still missing being able to pass the arguments to the ok and error actions.

I've made a PR for it: #8

**Comment by FredericHeem** [comment]
Version 0.8.0 has been released, it includes https://github.com/FredericHeem/redux-act-async/pull/8
